### ISSUE TITLE
OAuth needed

### ISSUE THREAD

**Issue by Artanicus** [dkhmelenko/Varis-Android#45] opened 2018-04-04 19:18 UTC
Asking for GitHub credentials is not acceptable.

**Comment by dkhmelenko** [comment] 2018-04-06 20:05
This is the way how Travis API v2 was implemented. The app itself doesn't store any credentials, only tokens.
There is a plan to migrate to API v3 and hopefully we don't need to have GitHub credentials anymore.

**Comment by dkhmelenko** [comment] 2018-11-05 17:30
@Artanicus Could you please confirm if #47 is the same as your request?

**Comment by dkhmelenko** [comment] 2018-11-05 17:32
Duplicate of #47

**Closed by dkhmelenko** 2018-11-05 17:32 UTC
